  
version: "3"
services:
  reverse-proxy:
    build:
      context: .
    image: khare123/reverse-proxy 
  backend_user:
    build:
      context: ../udacity-c2-restapi-user
    image: khare123/udacity-restapi-user
  backend_feed:
    build:
      context: ../udacity-c2-restapi-feed  
    image: khare123/udacity-restapi-feed
  frontend:
    build:
      context: ../udacity-c2-frontend  
    image: khare123/udacity-frontend:local