apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-deployment
  labels:
    app: reverse-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverse-proxy
  template:
    metadata:
      labels:
        app: reverse-proxy
    spec:
      containers:
      - name: reverse-proxy
        image: khare123/reverse-proxy:latest
        ports:
        - containerPort: 80